import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner"

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], 
});

export const metadata = {
  title: "Doctor Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-gray-50 text-gray-900`}>
        <div className="flex flex-col min-h-screen">
          {/* Header and Main Content */}
          <div className="flex-grow px-4 sm:px-6 lg:px-8 py-6">
            <Header />
            <main>
              {children}
              <Toaster />
            </main>
          </div>

          {/* Footer Section */}
          <div className="mt-auto">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
